module ProjMajster.Backend.Shake
  ( CommandRunner
  , CommandSpec(..)
  , DiscoveredSource(..)
  , ShakeTransformRunner
  , SourceManifest(..)
  , TransformInstance(..)
  , TransformRunnerRegistry(..)
  , builtinCommandTransformRunners
  , defaultTransformRunnerRegistry
  , sourceManifests
  , sourceDiscoveryRules
  , discoverSources
  , parseSourceManifestContent
  , planMapTransforms
  , planTargetTransforms
  , readSourceManifest
  , transformInstanceRules
  , transformInstanceRulesWith
  , transformRunnerRegistry
  ) where

import ProjMajster.Backend.Shake.SourceDiscovery
import ProjMajster.Backend.Shake.Transform
