module ProjMajster.Backend.Shake
  ( CommandRunner
  , CommandSpec(..)
  , DiscoveredSource(..)
  , ShakeTransformRunner
  , SourceManifest(..)
  , TransformManifest(..)
  , TransformInstance(..)
  , TransformRunnerRegistry(..)
  , builtinCommandTransformRunners
  , defaultTransformRunnerRegistry
  , sourceManifests
  , sourceDiscoveryRules
  , discoverSources
  , parseSourceManifestContent
  , parseTransformManifestContent
  , planMapTransforms
  , planTargetTransforms
  , readSourceManifest
  , readTransformManifest
  , targetBuildRules
  , targetBuildStampPath
  , transformManifest
  , transformManifestIndex
  , transformManifestPath
  , transformManifestProducts
  , transformManifestRules
  , transformOutputRulesWith
  , transformRunnerRegistry
  , writeTransformManifest
  ) where

import ProjMajster.Backend.Shake.SourceDiscovery
import ProjMajster.Backend.Shake.Transform
