name: projmajster
version: 0.1.0.0
license: BSD3
author: ""
maintainer: ""
copyright: ""

extra-source-files:
  - docs/*.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >= 4.14 && < 5
  - containers
  - directory
  - filepath
  - mtl
  - shake
  - text

library:
  source-dirs: src/lib
  exposed-modules:
    - ProjMajster
    - ProjMajster.Backend.Shake
    - ProjMajster.Backend.Shake.SourceDiscovery
    - ProjMajster.Core
    - ProjMajster.Core.BuildStyle
    - ProjMajster.Core.Dependency
    - ProjMajster.Core.FileRole
    - ProjMajster.Core.Install
    - ProjMajster.Core.Platform
    - ProjMajster.Core.Project
    - ProjMajster.Core.Settings
    - ProjMajster.Core.SourceSet
    - ProjMajster.Core.Target
    - ProjMajster.Core.Transform
    - ProjMajster.DSL
    - ProjMajster.DSL.Dependency
    - ProjMajster.DSL.Project
    - ProjMajster.DSL.Settings
    - ProjMajster.DSL.SourceSet
    - ProjMajster.DSL.Target
    - ProjMajster.Graph
    - ProjMajster.Graph.Build
    - ProjMajster.Graph.Types
    - ProjMajster.Plan
    - ProjMajster.Plan.Error
    - ProjMajster.Plan.Resolve
    - ProjMajster.Plan.Types
  other-modules:
    - ProjMajster.DSL.Internal

tests:
  projmajster-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - projmajster
